name: NuGet Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-dotnet@v1
      - name: Restore NuGet packages
        run: dotnet restore
      - name: Pack NuGet package
        run: |
          cd Source\Control\D.Diagram.Presenter.Workflow
          dotnet pack D.Diagram.Presenter.Workflow.csproj  --configuration Release
      - name: Publish NuGet package
        run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate