name: NuGet Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.x
            7.x
            8.x
            9.x
      - name: Restore NuGet packages
        run: dotnet restore
      - name: Pack NuGet package
        run: |
          dotnet pack  -c Release -o out Source\Control\D.Diagram.Presenter.Workflow\D.Diagram.Presenter.Workflow.csproj
      - name: Publish NuGet package
        run: dotnet nuget push .\out\*.nupkg --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NuGetAPIKey }}
